# Generated by Django 2.2.4 on 2019-09-03 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20190903_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='partition',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
