# Generated by Django 2.2.4 on 2019-09-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20190905_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='full_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
