# Generated by Django 2.2.4 on 2019-09-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificates_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
