# Generated by Django 2.2.4 on 2019-09-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_auto_20190906_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='bigip_name',
        ),
        migrations.DeleteModel(
            name='BigIPNodes',
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
