# Generated by Django 2.2.4 on 2020-01-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0008_auto_20190906_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertClientSSLVirtualServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_name', models.CharField(max_length=200)),
                ('cert_partition', models.CharField(max_length=200)),
                ('cert_expiration', models.DateTimeField()),
                ('cert_cluster', models.CharField(max_length=200)),
                ('cssl_name', models.CharField(max_length=200)),
                ('cssl_partition', models.CharField(max_length=200)),
                ('vs_name', models.CharField(max_length=200)),
                ('vs_partition', models.CharField(max_length=200)),
                ('vs_ip', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['cert_expiration'],
            },
        ),
    ]
