# Generated by Django 2.2.4 on 2020-03-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_certserversslvirtualserverviairuleanddatagroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='certclientsslvirtualserver',
            name='cert_common_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certclientsslvirtualserver',
            name='cert_san',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
