# Generated by Django 2.2.4 on 2019-09-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_profilesslclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigip_name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='profilesslclient',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='profilesslclient',
            name='updated_on',
        ),
    ]
