# Generated by Django 2.2.4 on 2019-09-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190925_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='country',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
