# Generated by Django 2.2.4 on 2019-10-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20191004_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualserver',
            name='profile_6',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='profile_7',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='profile_8',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='profile_9',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
