# Generated by Django 2.2.4 on 2019-12-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20191004_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigipnodes',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='bigipnodes',
            name='updated_on',
        ),
    ]
