# Generated by Django 2.2.4 on 2019-12-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_profilesslserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesslserver',
            name='bigip_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.BigIPNodes'),
        ),
    ]
