# Generated by Django 2.2.4 on 2019-12-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20191217_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesslserver',
            name='bigip_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.BigIPNodes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilesslserver',
            name='certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Certificates'),
        ),
    ]
