# Generated by Django 2.2.4 on 2019-12-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20191217_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualserver',
            name='profilesslserver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.ProfileSSLServer'),
        ),
        migrations.AlterField(
            model_name='profilesslclient',
            name='certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Certificates'),
        ),
    ]
