# Generated by Django 2.2.4 on 2020-01-02 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20191217_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualserver',
            name='profilesslclient',
        ),
        migrations.RemoveField(
            model_name='virtualserver',
            name='profilesslserver',
        ),
        migrations.AddField(
            model_name='profilesslclient',
            name='virtual_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.VirtualServer'),
        ),
        migrations.AddField(
            model_name='profilesslserver',
            name='virtual_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.VirtualServer'),
        ),
    ]
