# Generated by Django 2.2.4 on 2020-01-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20200103_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesslclient',
            old_name='certs_names',
            new_name='cert_names',
        ),
    ]
