# Generated by Django 2.2.4 on 2020-01-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20200103_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesslserver',
            name='certificate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.Certificates'),
            preserve_default=False,
        ),
    ]
