# Generated by Django 2.2.4 on 2020-01-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20200107_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesslserver',
            name='certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Certificates'),
        ),
    ]
