# Generated by Django 2.2.4 on 2020-02-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20200131_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datagroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('partition', models.CharField(max_length=200)),
                ('bigip_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.BigIPNodes')),
                ('profile_server_ssl', models.ManyToManyField(to='database.ProfileSSLServer')),
            ],
            options={
                'ordering': ['bigip_name'],
            },
        ),
        migrations.CreateModel(
            name='Irule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('partition', models.CharField(max_length=200)),
                ('bigip_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.BigIPNodes')),
                ('datagroup', models.ManyToManyField(to='database.Datagroup')),
            ],
            options={
                'ordering': ['bigip_name'],
            },
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='irule',
            field=models.ManyToManyField(to='database.Irule'),
        ),
    ]
