# Generated by Django 2.2.4 on 2020-02-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20200201_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='key_values',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilesslclient',
            name='cert_names',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='virtualserver',
            name='profiles',
            field=models.TextField(),
        ),
    ]
