# Generated by Django 2.2.4 on 2020-02-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_auto_20200201_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='irule',
            name='datagroups',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
