# Generated by Django 2.2.4 on 2020-02-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_irule_datagroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datagroup',
            name='key_values',
        ),
        migrations.AddField(
            model_name='datagroup',
            name='datagroup_profile_server_ssl',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datagroup',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='irules',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
