# Generated by Django 2.2.4 on 2020-04-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrulesNotAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irule_name', models.CharField(max_length=200)),
                ('irule_cluster', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['irule_cluster'],
            },
        ),
    ]
