# Generated by Django 2.2.4 on 2019-12-10 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0013_auto_20191004_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigIPNodePartionCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition_name', models.CharField(max_length=15)),
                ('partition_size', models.CharField(max_length=15)),
                ('partition_previous_size', models.CharField(max_length=15)),
                ('bigip_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.BigIPNodes')),
            ],
        ),
    ]
